version: '3.8'

services:
  db:
    container_name: pg_arm
    image: arm64v8/postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
    volumes:
      - postgres-arm-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
volumes:
  postgres-arm-data: