version: '3.8'
services:
  couchserver:
    image: arm64v8/couchdb
    restart: always
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdb
    volumes:
        - couchdb-data:/opt/couchdb/data
volumes:
  couchdb-data: