version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - my-mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
volumes:
  my-mongo: