scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'otel-collector:8889' ]
      - targets: [ 'otel-collector:8888' ]
  - job_name: 'support-test'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'host.docker.internal:8083' ]
  - job_name: 'service-customer----production'
    scrape_interval: 15s
    static_configs:
      - targets: [ '172.31.5.60:21631' ]
      - targets: [ '172.31.14.145:22213' ]
      - targets: [ '172.31.0.30:24100' ]