version: '3.8'

services:

  db:
    container_name: pg_container
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pgdb
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
  # pgadmin:
  #   container_nsame: pgadmin4_container
  #   image: dpage/pgadmin4
  #   restart: on-failure
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: postgres
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
volumes:
  postgres-data:
  # pgadmin-data: